### PR TITLE
Export worflow params

### PR DESCRIPTION
**Pull request by darcyparker**
@dhilt: While working on https://github.com/dhilt/vscroll-native/issues/2, I had a minor issue trying to improve some type annotations.

`WorkflowParams` is re-defined here: 
https://github.com/dhilt/vscroll-native/blob/d422f6806182e5a174f9a3160a137701b88526ed/src/workflow-storage.ts#L10

But it doesn't retain the generic type in its definition.  This means `MyWorkflowParams` does not have alignment of the `Data` type other than it is unknown...  In `WorkflowStorage`, I'd like to define `add<MyItem>(params: MyWorkflowParams<MyItem>): Id`, so that the data type in the `datasource` and `onItemsChanged` handler have aligned data types.

I also added `.node-version` and made some `package.json` updates and updated `package-lock.json` to v2 which provides reproducible builds. If you're not comfortable with these changes, I can remove them.

### CODE REVIEW

**Comment by dhilt** [comment]
@darcyparker I absolutely agree with exporting `WorkflowParams` type (the doc [relies on it](https://github.com/dhilt/vscroll#usage)), I have no objection to package-lock.json v2 (and npm 7), but I prefer not to switch to node v16 since it is not an "active" version (Active LTS will start from 2021-10-26). And why do we might need to fix node version?

Also, do you know, is package-lock.json v2 backward-compatible with previous versions? Doesn't that make us fix the npm engine? for example like in package.json:

```js
  "engines": {
    "npm": ">= 7.0.0"
  },
```

?

**Comment by darcyparker** [comment]
Good point about `engines`.  I can remove the `.node-version` and `.nvrmc`.  We don't need to fix the node version for development. When I have multiple projects, I find it easier to have a `.node-version` file to help me switch versions to one that works. But you're right that v16 is too new.

**Comment by dhilt** [comment]
Merged into a dev branch, we'll accumulate changes [there](https://github.com/dhilt/vscroll/pull/30) before the release.

**Comment by dhilt** [comment]
If it's necessary I can publish alpha version of the updated core, but it would be better to follow local dev workflow until any significant result.

**Comment by darcyparker** [comment]
`dev` branch is good. Thanks.   This [tip](https://github.com/dhilt/vscroll-native/issues/2#issuecomment-934047312) you gave me worked.

**Pull request merged**
